"""attempt.used_choices

Revision ID: 70f59c7a0e68
Revises: 2948bf05115e
Create Date: 2026-08-09 17:06:57.077178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70f59c7a0e68'
down_revision: Union[str, None] = '2948bf05115e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('used_choices', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'used_choices')
    # ### end Alembic commands ###
