"""episode last_opened_at

Revision ID: 9428a550ee2e
Revises: 96dc13046287
Create Date: 2026-08-09 18:59:49.133063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9428a550ee2e'
down_revision: Union[str, None] = '96dc13046287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_episode_progress', sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_episode_progress', 'last_opened_at')
    # ### end Alembic commands ###
