"""episode progress steps

Revision ID: 96dc13046287
Revises: ad0647d622e3
Create Date: 2026-08-09 17:44:03.007271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '96dc13046287'
down_revision: Union[str, None] = 'ad0647d622e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 기존 행이 있어도 안전하도록 server_default. 신규 행 기본값은 모델이 결정한다.
    op.add_column('user_episode_progress', sa.Column('video_done', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user_episode_progress', sa.Column('point_done', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user_episode_progress', sa.Column('practice_done', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_episode_progress', 'practice_done')
    op.drop_column('user_episode_progress', 'point_done')
    op.drop_column('user_episode_progress', 'video_done')
    # ### end Alembic commands ###
