"""vocab_favorites

Revision ID: ad0647d622e3
Revises: 70f59c7a0e68
Create Date: 2026-08-09 17:15:10.342725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad0647d622e3'
down_revision: Union[str, None] = '70f59c7a0e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'vocab_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab_favorites')
    # ### end Alembic commands ###
